config-* scripts learn start/stop argument, while ifup/ifdown scripts try to use it IP functions go from functions file info config-ipv4/config-ipv6
git-svn-id: svn://svn.etcnet.org/trunk/etcnet@723 4788b5ed-9404-0410-8295-8f3c5ce22fc0

diff --git a/etc/net/scripts/config-ipv4 b/etc/net/scripts/config-ipv4
--- a/etc/net/scripts/config-ipv4
+++ b/etc/net/scripts/config-ipv4
@@ -1,121 +1,177 @@
 #!/bin/bash
 
+usage()
+{
+	echo '/etc/net IPv4 handler'
+	echo "Usage: $0 <interface> <start|stop>" >&2
+	exit 1
+}
+
+[ $# -eq 2 ] || usage
+NAME=$1
+ACTION=$2
 pickup_defaults
 pickup_options
 
-try_static()
+# operation\first word | add X | del X | Y X
+#----------------------+-------+-------+------
+# add                  | add X | del X | add X
+#----------------------+-------+-------+------
+# del                  | del X | del X | del X
+#----------------------+-------+-------+------
+process_ipv4rules()
 {
-	xargise_file $MYIFACEDIR/ipv4address "$IP -4 address add dev $NAME"
-}
-
-try_dhcp()
-{
-	[ -x "$DHCP_CLIENT" ] || {
-		print_error "$DHCP_CLIENT does not exist or is not executable. Try installing dhcpcd RPM."
-		return 1
-	}
-	if need_detection; then
-		if check_eth_link $NAME; then
-			print_progress
-		else
-			print_nack
-			return 1
-		fi
-	fi
-	if [ -n "$DHCP_HOSTNAME" ]; then
-		case "$DHCP_HOSTNAME" in
-			AUTO)
-				DHCP_ARGS="$DHCP_ARGS -H"
-			;;
-			localhost)
-				[ -n "$HOSTNAME" -a "$HOSTNAME" != "localhost" -a "$HOSTNAME" != "localhost.localdomain" ] && DHCP_ARGS="$DHCP_ARGS -h $HOSTNAME"
-			;;
-			*)
-				DHCP_ARGS="$DHCP_ARGS -h $DHCP_HOSTNAME"
-			;;
-		esac
-	fi
-	$DHCP_CLIENT $DHCP_ARGS -d -t $DHCP_TIMEOUT $NAME >/dev/null
-	local RET=$?
-	# dhcpcd sets iface down on failure, breaking dhcp-* BOOTPROTOs
-	if [ "$RET" != "0" ]; then
-		print_nack
-		! is_yes $KEEP_DOWN && $IP link set dev $NAME up
-	else
-		print_progress
-	fi
-	return $RET
-}
-
-try_ipv4ll()
-{
-	[ -x "$ZCIP_CLIENT" ] || {
-		print_error "$ZCIP_CLIENT does not exist or is not executable. Try installing zcip RPM."
-		return 1
-	}
-	if need_detection; then
-		if check_eth_link $NAME; then
-			print_progress
-		else
-			print_nack
-			return 1
-		fi
-	fi
-	$ZCIP_CLIENT -s -i $NAME
-	local RET=$?
-	if [ "$RET" != "0" ]; then
-		print_nack
-	else
-		print_progress
-	fi
-	return $RET
-}
-
-config_ipv4_routes_rules()
-{
-	# setup routes
-	local SRCFILE=`profiled_filename $MYIFACEDIR/ipv4route`
+	local OP=${1:?missing 1st arg to $FUNCNAME}
+	SRCFILE=`profiled_filename $MYIFACEDIR/ipv4rule`
 	[ -s "$SRCFILE" ] && $DENOISE "$SRCFILE" | \
 	while read FIRST REST; do
-	# If there is no operation, substitute default, otherwise keep.
 		case "$FIRST" in
-			add|del|change|append|replace)
-				$IP -4 route $FIRST $REST dev $NAME
+			add)
+				[ $OP = "del" ] && FIRST=del
+			;;
+			del)
+				# should we restore deleted rules on iface shutdown?
+				# [ $OP = "del" ] && FIRST=add
 			;;
 			*)
-				$IP -4 route append $FIRST $REST dev $NAME
+				FIRST="$OP $FIRST"
 			;;
 		esac
+		$IP -4 rule $FIRST $REST
 		print_progress
 	done
-
-	# Setup rules only after routes are Ok, so that route tables are
-	# already populated when rule starts routing traffic to them.
-	process_ipv4rules add
 }
 
-if iface_is_up $NAME; then
-	case "$BOOTPROTO" in
-		static)
-			try_static && config_ipv4_routes_rules
-			;;
-		dhcp)
-			try_dhcp && config_ipv4_routes_rules
-			;;
-		ipv4ll)
-			try_ipv4ll && config_ipv4_routes_rules
-			;;
-		dhcp-static)
-			try_dhcp || try_static && config_ipv4_routes_rules
-			;;
-		dhcp-ipv4ll)
-			try_dhcp || try_ipv4ll && config_ipv4_routes_rules
-			;;
-		dhcp-ipv4ll-static)
-			try_dhcp || try_ipv4ll || try_static && config_ipv4_routes_rules
-			;;
-		*)
-			print_error "unknown BOOTPROTO '$BOOTPROTO'"
-			;;
-	esac
-fi
+case $ACTION
+	start)
+		try_static()
+		{
+			xargise_file $MYIFACEDIR/ipv4address "$IP -4 address add dev $NAME"
+		}
+
+		try_dhcp()
+		{
+			[ -x "$DHCP_CLIENT" ] || {
+				print_error "$DHCP_CLIENT does not exist or is not executable. Try installing dhcpcd RPM."
+				return 1
+			}
+			if need_detection; then
+				if check_eth_link $NAME; then
+					print_progress
+				else
+					print_nack
+					return 1
+				fi
+			fi
+			if [ -n "$DHCP_HOSTNAME" ]; then
+				case "$DHCP_HOSTNAME" in
+					AUTO)
+						DHCP_ARGS="$DHCP_ARGS -H"
+					;;
+					localhost)
+						[ -n "$HOSTNAME" -a "$HOSTNAME" != "localhost" -a "$HOSTNAME" != "localhost.localdomain" ] && DHCP_ARGS="$DHCP_ARGS -h $HOSTNAME"
+					;;
+					*)
+						DHCP_ARGS="$DHCP_ARGS -h $DHCP_HOSTNAME"
+					;;
+				esac
+			fi
+			$DHCP_CLIENT $DHCP_ARGS -d -t $DHCP_TIMEOUT $NAME >/dev/null
+			local RET=$?
+			# dhcpcd sets iface down on failure, breaking dhcp-* BOOTPROTOs
+			if [ "$RET" != "0" ]; then
+				print_nack
+				! is_yes $KEEP_DOWN && $IP link set dev $NAME up
+			else
+				print_progress
+			fi
+			return $RET
+		}
+
+		try_ipv4ll()
+		{
+			[ -x "$ZCIP_CLIENT" ] || {
+				print_error "$ZCIP_CLIENT does not exist or is not executable. Try installing zcip RPM."
+				return 1
+			}
+			if need_detection; then
+				if check_eth_link $NAME; then
+					print_progress
+				else
+					print_nack
+					return 1
+				fi
+			fi
+			$ZCIP_CLIENT -s -i $NAME
+			local RET=$?
+			if [ "$RET" != "0" ]; then
+				print_nack
+			else
+				print_progress
+			fi
+			return $RET
+		}
+
+		config_ipv4_routes_rules()
+		{
+			# setup routes
+			local SRCFILE=`profiled_filename $MYIFACEDIR/ipv4route`
+			[ -s "$SRCFILE" ] && $DENOISE "$SRCFILE" | \
+			while read FIRST REST; do
+			# If there is no operation, substitute default, otherwise keep.
+				case "$FIRST" in
+					add|del|change|append|replace)
+						$IP -4 route $FIRST $REST dev $NAME
+					;;
+					*)
+						$IP -4 route append $FIRST $REST dev $NAME
+					;;
+				esac
+				print_progress
+			done
+
+			# Setup rules only after routes are Ok, so that route tables are
+			# already populated when rule starts routing traffic to them.
+			process_ipv4rules add
+		}
+
+		if iface_is_up $NAME; then
+			is_yes $DONT_FLUSH || {
+				$IP -4 address flush dev $NAME >/dev/null 2>&1
+				print_progress
+			}
+			case "$BOOTPROTO" in
+				static)
+					try_static && config_ipv4_routes_rules
+					;;
+				dhcp)
+					try_dhcp && config_ipv4_routes_rules
+					;;
+				ipv4ll)
+					try_ipv4ll && config_ipv4_routes_rules
+					;;
+				dhcp-static)
+					try_dhcp || try_static && config_ipv4_routes_rules
+					;;
+				dhcp-ipv4ll)
+					try_dhcp || try_ipv4ll && config_ipv4_routes_rules
+					;;
+				dhcp-ipv4ll-static)
+					try_dhcp || try_ipv4ll || try_static && config_ipv4_routes_rules
+					;;
+				*)
+					print_error "unknown BOOTPROTO '$BOOTPROTO'"
+					;;
+			esac
+		fi
+	;;
+	#------------------------------------------------------ 'start' case ends
+	stop)
+		process_ipv4rules del
+		$IP -4 address flush dev $NAME >/dev/null 2>&1
+	;;
+	#------------------------------------------------------ 'stop' case ends
+	*)
+		print_error "Illegal argument to $0: '$ACTION'"
+	;;
+esac
diff --git a/etc/net/scripts/config-qos b/etc/net/scripts/config-qos
--- a/etc/net/scripts/config-qos
+++ b/etc/net/scripts/config-qos
@@ -1,70 +1,78 @@
 #!/bin/bash
 
-# This script handles QoS configuration for given iface name.
-
 usage()
 {
-	echo "Usage: $0 <interface>" >&2
+	echo '/etc/net QoS handler'
+	echo "Usage: $0 <interface> <start|stop>" >&2
 	exit 1
 }
 
-# process_qos_dir <current dir> <parent> [last qdisc handle] [extra]
-process_qos_dir ()
-{
-	local NODENAME NODETYPE NODEIDPREFIX NODEATTRS NODEID
-	local NODEDIR=${1:?missing 1st arg to $FUNCNAME}
-	local NODENAME=${NODEDIR//*\//}
-	# this arg is 'root' for the first call and 'parent x:y' for the rest
-	local PARENTNODE=${2:?missing 2nd arg to $FUNCNAME}
-	local LAST_QDISC_HANDLE=$3
-	local EXTRAATTRS=$4
-	if [ -f $NODEDIR/class ]; then
-		NODETYPE=class
-		NODEIDPREFIX=classid
-		NODEID="$LAST_QDISC_HANDLE$NODENAME"
-		NODEATTRS="`head -1 $NODEDIR/class`"
-	elif [ -f $NODEDIR/qdisc ]; then
-		NODETYPE=qdisc
-		NODEIDPREFIX=handle
-		NODEID="$NODENAME:"
-		LAST_QDISC_HANDLE=$NODEID
-		NODEATTRS=`head -1 $NODEDIR/qdisc`
-	else
-		print_error "Unknown node type in $FUNCNAME, TDIR=$NODEDIR"
-		return 1
-	fi
-	$TC $NODETYPE add dev $NAME $PARENTNODE $NODEIDPREFIX $NODEID $EXTRAATTRS $NODEATTRS
-# setup filters
-	if [ $NODETYPE = class -a -s $NODEDIR/filter ]; then
-		$DENOISE $NODEDIR/filter | while read FILTEREXPR; do
-			$TC filter add dev $NAME $PARENTNODE `head -1 $NODEDIR/extra.filter 2>/dev/null` $FILTEREXPR flowid $NODEID
-		done
-	fi
-	RECLEVEL=$((RECLEVEL+1))
-	for d in $NODEDIR/*; do
-		[ -d $d ] && $FUNCNAME $d "parent $NODEID" "$LAST_QDISC_HANDLE" "`head -1 $NODEDIR/extra 2>/dev/null`"
-	done
-	RECLEVEL=$((RECLEVEL-1))
-	return 0
-}
-
-[ -z "$1" ] && usage
-NAME=$1
-
 [ -d $MYIFACEDIR/qos/ -a -x $MYIFACEDIR/qos/ ] || exit 0
+[ $# -eq 2 ] || usage
+NAME=$1
+ACTION=$2
 pickup_defaults
 pickup_options
 
-# clean up
-$TC qdisc del dev $NAME root >/dev/null 2>&1
+case $ACTION
+	start)
+		# process_qos_dir <current dir> <parent> [last qdisc handle] [extra]
+		process_qos_dir()
+		{
+			local NODENAME NODETYPE NODEIDPREFIX NODEATTRS NODEID
+			local NODEDIR=${1:?missing 1st arg to $FUNCNAME}
+			local NODENAME=${NODEDIR//*\//}
+			# this arg is 'root' for the first call and 'parent x:y' for the rest
+			local PARENTNODE=${2:?missing 2nd arg to $FUNCNAME}
+			local LAST_QDISC_HANDLE=$3
+			local EXTRAATTRS=$4
+			if [ -f $NODEDIR/class ]; then
+				NODETYPE=class
+				NODEIDPREFIX=classid
+				NODEID="$LAST_QDISC_HANDLE$NODENAME"
+				NODEATTRS="`head -1 $NODEDIR/class`"
+			elif [ -f $NODEDIR/qdisc ]; then
+				NODETYPE=qdisc
+				NODEIDPREFIX=handle
+				NODEID="$NODENAME:"
+				LAST_QDISC_HANDLE=$NODEID
+				NODEATTRS=`head -1 $NODEDIR/qdisc`
+			else
+				print_error "Unknown node type in $FUNCNAME, TDIR=$NODEDIR"
+				return 1
+			fi
+			$TC $NODETYPE add dev $NAME $PARENTNODE $NODEIDPREFIX $NODEID $EXTRAATTRS $NODEATTRS
+		# setup filters
+			if [ $NODETYPE = class -a -s $NODEDIR/filter ]; then
+				$DENOISE $NODEDIR/filter | while read FILTEREXPR; do
+					$TC filter add dev $NAME $PARENTNODE `head -1 $NODEDIR/extra.filter 2>/dev/null` $FILTEREXPR flowid $NODEID
+				done
+			fi
+			RECLEVEL=$((RECLEVEL+1))
+			for d in $NODEDIR/*; do
+				[ -d $d ] && $FUNCNAME $d "parent $NODEID" "$LAST_QDISC_HANDLE" "`head -1 $NODEDIR/extra 2>/dev/null`"
+			done
+			RECLEVEL=$((RECLEVEL-1))
+			return 0
+		}
+		# clean up
+		$TC qdisc del dev $NAME root >/dev/null 2>&1
 
-# do the rest
-cd $MYIFACEDIR/qos/
-export RECLEVEL=0
-# process only the first dir
-for d in $MYIFACEDIR/qos/*; do
-	[ -d $d ] && {
-		process_qos_dir $d root && print_progress
-		break
-	}
-done
+		# do the rest
+		cd $MYIFACEDIR/qos/
+		export RECLEVEL=0
+		# process only the first dir
+		for d in $MYIFACEDIR/qos/*; do
+			[ -d $d ] && {
+				process_qos_dir $d root && print_progress
+				break
+			}
+		done
+	;;
+	stop)
+		$TC qdisc del dev $NAME root >/dev/null 2>&1
+	;;
+	*)
+		print_error "Illegal argument to $0: '$ACTION'"
+	;;
+esac
