initconf seems to understand tunnels better
git-svn-id: svn://svn.etcnet.org/trunk/etcnet@315 4788b5ed-9404-0410-8295-8f3c5ce22fc0

diff --git a/etc/net/scripts/initconf b/etc/net/scripts/initconf
--- a/etc/net/scripts/initconf
+++ b/etc/net/scripts/initconf
@@ -8,20 +8,17 @@ IFACEDIR=${IFACEDIR:-/etc/net/ifaces}
 if [ "$1" = "write" ]; then
 	TESTMODE=no
 	[ -d "$IFACEDIR" ] || {
-		echo "ERROR: $IFACEDIR does not exist"
+		echo "ERROR: $IFACEDIR does not exist, exiting"
 		exit 1
 	}
 fi
 
 [ -x ${IP:=/sbin/ip} ] || {
-	echo "ERROR: $IP is not available"
+	echo "ERROR: $IP is not available, exiting"
 	exit 1
 }
 
-[ -x ${ETHTOOL:=/usr/sbin/ethtool} ] || {
-	echo "ERROR: $ETHTOOL is not available"
-	exit 1
-}
+[ -x ${ETHTOOL:=/usr/sbin/ethtool} ] || echo "WARNING: $ETHTOOL is not available, module detection will be skipped"
 
 IFTAB=/etc/net/iftab
 
@@ -49,35 +46,68 @@ function makedir()
 	fi
 }
 
+# broadcast multiple access
+function print_ipv4_BMA_addresses()
+{
+	local IFNAME=${1:?missing 1st arg to $FUNCNAME}
+	$IP -4 ad sh dev $IFNAME | grep '^ *inet' | sed 's/^ *inet //' | cut --delimiter=' ' --fields=1 | tr '\n' '\t' | sed 's/\t/ NEWLINE /g' | sed 's/ NEWLINE /\\n/g'
+}
+
+# peer-to-peer
+function print_ipv4_P2P_addresses()
+{
+	local IFNAME=${1:?missing 1st arg to $FUNCNAME}
+	$IP -4 ad sh dev $IFNAME | grep '^ *inet' | sed 's/^ *inet //' | cut --delimiter=' ' --fields=1-3 | tr '\n' '\t' | sed 's/\t/ NEWLINE /g' | sed 's/ NEWLINE /\\n/g'
+}
+
 for iface in `$IP li | egrep '^[[:digit:]]+: ' | cut --delimiter=' ' --fields=2 | sed 's/://' | sed 's/@NONE$//'`; do
 	echo -n "Processing interface '$iface':"
 	if [ -d $IFACEDIR/$iface ]; then
 		echo " configuration exists"
 		continue
 	fi
-	# pickup explicit ethernets only
-	if [ "${iface//[0-9]*/}" = "eth" ]; then
-		# find and use link-level address
-		if $IP li sh dev $iface | fgrep -q 'link/ether'; then
-			LLADDR=`$IP li sh dev $iface | fgrep 'link/ether' | sed 's/^ *link\/ether //' | cut --delimiter=' ' --fields=1`
-			if [ "$LLADDR" != "00:00:00:00:00:00" ]; then
-				store $IFTAB "# Generated by /etc/net initconf script\n$iface mac $LLADDR\n"
-			fi
-			makedir $IFACEDIR/$iface
-			store $IFACEDIR/$iface/options "# If you want to change current interface name, edit $IFTAB,\n# rename current directory and uncomment this line:\n#TYPE=eth\n"
-		fi
-		# find module
-		MODULE=`ethtool -i $iface | fgrep 'driver: ' | cut --delimiter=' ' --fields=2`
-		if [ -n "$MODULE" ]; then
-			store $IFACEDIR/$iface/options "# Uncomment this line if you don't have modules.conf alias for this interface\n# and don't intend to use hotplug configuration.\n#MODULE=$MODULE\n"
-			store $IFTAB "# Generated by /etc/net initconf script\n#$iface driver $MODULE\n"
-		fi
+	if [ "$iface" = "gre0" -o "$iface" = "tunl0" ]; then
+		echo " skipped pseudo-interface"
+		continue
 	fi
-	# dump IPv4 info
-	IPV4ADDRS=`$IP -4 ad sh dev $iface | grep '^    inet' | sed 's/^    inet //' | cut --delimiter=' ' --fields=1 | tr '\n' '\t' | sed 's/\t/ NEWLINE /g' | sed 's/ NEWLINE /\\\\n/g'`
-	#echo "$IPV4ADDRS"
-	[ -n "$IPV4ADDRS" ] && store $IFACEDIR/$iface/ipv4address $IPV4ADDRS
-	IPV4ROUTES=`$IP -4 ro ls dev $iface type unicast scope global | tr '\n' '\t' | sed 's/\t/ NEWLINE /g' | sed 's/ NEWLINE /\\\\n/g'`
+	LINKTYPE=`$IP li sh dev $iface | fgrep 'link/' | sed 's/^ *link\///' | cut --delimiter=' ' --fields=1`
+	if [ -n "$LINKTYPE" ]; then
+		# try to find linktype-specific options
+		case "$LINKTYPE" in
+			ether)
+				# many others try to look as ethernet, so let's filter by iface name...
+				if [ "${iface//[0-9]*/}" = "eth" ]; then
+					# find and use link-level address
+					LLADDR=`$IP li sh dev $iface | fgrep 'link/ether' | sed 's/^ *link\/ether //' | cut --delimiter=' ' --fields=1`
+					# ...and by valid MAC address
+					if [ "$LLADDR" != "00:00:00:00:00:00" ]; then
+						store $IFTAB "# Generated by /etc/net initconf script\n$iface mac $LLADDR\n"
+					fi
+					makedir $IFACEDIR/$iface
+					store $IFACEDIR/$iface/options "# If you want to change current interface name, edit $IFTAB,\n# rename current directory and uncomment this line:\n#TYPE=eth\n"
+					# find module
+					if [ -x "$ETHTOOL" ]; then
+						MODULE=`ethtool -i $iface | fgrep 'driver: ' | cut --delimiter=' ' --fields=2`
+						if [ -n "$MODULE" ]; then
+							store $IFACEDIR/$iface/options "# Uncomment this line if you don't have modules.conf alias for this interface\n# and don't intend to use hotplug configuration.\n#MODULE=$MODULE\n"
+							store $IFTAB "# Generated by /etc/net initconf script\n#$iface driver $MODULE\n"
+						fi
+					fi
+				fi
+				IPV4ADDRS=`print_ipv4_BMA_addresses $iface`
+			;;
+			gre|ipip)
+				store $IFACEDIR/$iface/options "TUNTYPE=$LINKTYPE"
+				CARRIER_LOCAL=`ip tu sh $iface | sed 's/  /\n/g' | grep '^local ' | cut --delimiter=' ' --fields=2`
+				CARRIER_REMOTE=`ip tu sh $iface | sed 's/  /\n/g' | grep '^remote ' | cut --delimiter=' ' --fields=2`
+				[ -n "$CARRIER_LOCAL" ] && store $IFACEDIR/$iface/options "PHYSLOCAL=$CARRIER_LOCAL"
+				[ -n "$CARRIER_REMOTE" ] && store $IFACEDIR/$iface/options "PHYSREMOTE=$CARRIER_REMOTE"
+				IPV4ADDRS=`print_ipv4_P2P_addresses $iface`
+			;;
+		esac
+	fi
+	[ -n "$IPV4ADDRS" ] && store $IFACEDIR/$iface/ipv4address "$IPV4ADDRS"
+	IPV4ROUTES=`$IP -4 ro ls dev $iface type unicast scope global | fgrep -v 'proto zebra' | tr '\n' '\t' | sed 's/\t/ NEWLINE /g' | sed 's/ NEWLINE /\\\\n/g'`
 	[ -n "$IPV4ROUTES" ] && store $IFACEDIR/$iface/ipv4route "$IPV4ROUTES"
 	echo ' finished'
 done
