better portability
git-svn-id: svn://svn.etcnet.org/trunk/etcnet@423 4788b5ed-9404-0410-8295-8f3c5ce22fc0

diff --git a/etc/net/scripts/network.init b/etc/net/scripts/network.init
--- a/etc/net/scripts/network.init
+++ b/etc/net/scripts/network.init
@@ -8,6 +8,10 @@
 WITHOUT_RC_COMPAT=1
 
 SCRIPTDIR=/etc/net/scripts
+if [ ! -s $SCRIPTDIR/functions ]; then
+	echo "Error: $SCRIPTDIR/functions not found!"
+	exit 1
+fi
 . $SCRIPTDIR/functions
 SourceIfNotEmpty /etc/sysconfig/network
 export IFACEDIR SCRIPTDIR NETPROFILE NETHOST
@@ -401,9 +405,10 @@ check()
 		fi
 	done
 }
+
 usage()
 {
-	msg_usage "${0##*/} {start|startwith|stop|stopwith|restart|reload|restartwith|switchto <new profile name>}"
+	echo "${0##*/} {start|startwith|stop|stopwith|restart|reload|restartwith|switchto <new profile name>}"
 	exit 1
 }
 
